### ISSUE TITLE
Trait 'Illuminate\Foundation\Bus\DispatchesCommands' not found

### ISSUE THREAD

**Issue by AmrAlfoly** [tabacitu/menumanager#2]
i got this error after installing the package
when i searched the error i found that :
Trait 'Illuminate\Foundation\Bus\DispatchesCommands' was deprecated and replaced by :
Trait 'Illuminate\Foundation\Bus\DispatchesJobs'
so please fix this

**Comment by tabacitu** [comment]
Hi @AmrAlfoly ! Thanks a lot for the solution. One question: are you running Laravel 5.1.x or 5.2.x?
Thanks!

**Comment by AmrAlfoly** [comment]
Hi @tabacitu  i am using Laravel 5.2.x
i hope this helps
